# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moon < Formula
  desc "A powerful game development AI agent that can build complete games from scratch. Expert in Unity, Unreal Engine, and Godot."
  homepage "https://moonforge.com"
  version "0.19.1"
  license "FSL-1.1-MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MoonForgeAI/moon/releases/download/v0.19.1/moon_0.19.1_Darwin_x86_64.tar.gz"
      sha256 "3a4838b040df0ada31c5319b8a5e28cc6757690a2eb38e7f8c65c46deba27c85"

      def install
        bin.install "moon"
        bash_completion.install "completions/moon.bash" => "moon"
        zsh_completion.install "completions/moon.zsh" => "_moon"
        fish_completion.install "completions/moon.fish"
        man1.install "manpages/moon.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MoonForgeAI/moon/releases/download/v0.19.1/moon_0.19.1_Darwin_arm64.tar.gz"
      sha256 "de2dd399f3bdaa9bb2acde0888bd13eb18273cd125043681d85bee5b539b8d91"

      def install
        bin.install "moon"
        bash_completion.install "completions/moon.bash" => "moon"
        zsh_completion.install "completions/moon.zsh" => "_moon"
        fish_completion.install "completions/moon.fish"
        man1.install "manpages/moon.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MoonForgeAI/moon/releases/download/v0.19.1/moon_0.19.1_Linux_x86_64.tar.gz"
      sha256 "11d88e14770d36798b895f51dcb22806b1361492fba0e89c93f1386e8ef6242c"
      def install
        bin.install "moon"
        bash_completion.install "completions/moon.bash" => "moon"
        zsh_completion.install "completions/moon.zsh" => "_moon"
        fish_completion.install "completions/moon.fish"
        man1.install "manpages/moon.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/MoonForgeAI/moon/releases/download/v0.19.1/moon_0.19.1_Linux_armv7.tar.gz"
      sha256 "5cf0880a2c1eb95cf0c9575014de31765e98c6ee31608b18b97d55bd5e9bf993"
      def install
        bin.install "moon"
        bash_completion.install "completions/moon.bash" => "moon"
        zsh_completion.install "completions/moon.zsh" => "_moon"
        fish_completion.install "completions/moon.fish"
        man1.install "manpages/moon.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MoonForgeAI/moon/releases/download/v0.19.1/moon_0.19.1_Linux_arm64.tar.gz"
      sha256 "4f622bff2ad0e35ce6d81832240050d5e24f879669284b6575ea82b0176df2ef"
      def install
        bin.install "moon"
        bash_completion.install "completions/moon.bash" => "moon"
        zsh_completion.install "completions/moon.zsh" => "_moon"
        fish_completion.install "completions/moon.fish"
        man1.install "manpages/moon.1.gz"
      end
    end
  end
end
