# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moon < Formula
  desc "A powerful game development AI agent that can build complete games from scratch. Expert in Unity, Unreal Engine, and Godot."
  homepage "https://moonforge.com"
  version "0.19.3"
  license "FSL-1.1-MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MoonForgeAI/moon/releases/download/v0.19.3/moon_0.19.3_Darwin_x86_64.tar.gz"
      sha256 "5374970c9ceaa8b4ff4f32867f9528dec1a9ba888a0968f066cb3d1f6607a625"

      def install
        bin.install "moon"
        bash_completion.install "completions/moon.bash" => "moon"
        zsh_completion.install "completions/moon.zsh" => "_moon"
        fish_completion.install "completions/moon.fish"
        man1.install "manpages/moon.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MoonForgeAI/moon/releases/download/v0.19.3/moon_0.19.3_Darwin_arm64.tar.gz"
      sha256 "10392d2a36c923885fd530d6c966eb4de2d8c7e87591f1daf51df27c5ebb537b"

      def install
        bin.install "moon"
        bash_completion.install "completions/moon.bash" => "moon"
        zsh_completion.install "completions/moon.zsh" => "_moon"
        fish_completion.install "completions/moon.fish"
        man1.install "manpages/moon.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MoonForgeAI/moon/releases/download/v0.19.3/moon_0.19.3_Linux_x86_64.tar.gz"
      sha256 "8190ed4a503b99024d8d1670f5b06dfdd0d5d67be07dcad3547ca29eec2b7419"
      def install
        bin.install "moon"
        bash_completion.install "completions/moon.bash" => "moon"
        zsh_completion.install "completions/moon.zsh" => "_moon"
        fish_completion.install "completions/moon.fish"
        man1.install "manpages/moon.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/MoonForgeAI/moon/releases/download/v0.19.3/moon_0.19.3_Linux_armv7.tar.gz"
      sha256 "cbacd60b18d743f30ff9c0e23144fbdd3c7a8c1b9fb73d025b2a4a358897cb32"
      def install
        bin.install "moon"
        bash_completion.install "completions/moon.bash" => "moon"
        zsh_completion.install "completions/moon.zsh" => "_moon"
        fish_completion.install "completions/moon.fish"
        man1.install "manpages/moon.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MoonForgeAI/moon/releases/download/v0.19.3/moon_0.19.3_Linux_arm64.tar.gz"
      sha256 "289c33bc77f3a42d6db7472b6287dfe91e2a3e141bede53d53aec87e89b08667"
      def install
        bin.install "moon"
        bash_completion.install "completions/moon.bash" => "moon"
        zsh_completion.install "completions/moon.zsh" => "_moon"
        fish_completion.install "completions/moon.fish"
        man1.install "manpages/moon.1.gz"
      end
    end
  end
end
